# Basic
title: 岁寒
subtitle: 疾风知劲草，岁寒见后凋。
welcome_message: <a href="https://github.com/Hymnhyz/Hymnhyz.github.io" target="_blank">Download the theme</a>
description: 个人博客。
creator: <a href="http://onev.cat">@onevcat</a>

url: "https://hymnhyz.github.io/#blog"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/Hymnhyz'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 
    github: Hymnhyz
    twitter: 
    gplus: 107108267983477358170
    mail: yz.hu@foxmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
